In [2]:
import os

os.makedirs(os.path.join('..', 'datasets'), exist_ok=True)
data_file = os.path.join('..', 'datasets', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [3]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [8]:
import numpy as np

# 选择数值列并计算平均值
# 这会忽略 'Alley' 列
means = inputs.select_dtypes(include=np.number).mean()

# 使用计算出的平均值进行填充
# Pandas 会自动将 'NumRooms' 的平均值填充到 'NumRooms' 列的 NaN 位置
inputs.fillna(means, inplace=True)

# 打印最终结果
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [10]:
inputs =pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


In [13]:
import tensorflow as tf

X = tf.constant(inputs.to_numpy(dtype=float))
y = tf.constant(outputs.to_numpy(dtype=float))
X, y

(<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
 array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]])>,
 <tf.Tensor: shape=(4,), dtype=float64, numpy=array([127500., 106000., 178100., 140000.])>)

In [15]:
data2 = data2.iloc[:, data2.isna().sum().values < data2.isna().sum().max()]

NameError: name 'data2' is not defined