In [3]:
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [4]:
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """构造一个TensorFlow数据迭代器"""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [13]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 1.4893348 ,  2.0870013 ],
        [-0.8604161 ,  0.09312131],
        [ 0.57311726, -0.35419077],
        [ 0.1657205 , -0.04936584],
        [-0.53297627,  2.7045105 ],
        [ 0.5312142 , -1.0097433 ],
        [ 0.0870741 ,  0.83976233],
        [ 1.0324683 ,  0.52178055],
        [-0.20697817, -0.83079   ],
        [ 0.16860516,  1.5866791 ]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 0.08555359],
        [ 2.1699927 ],
        [ 6.5440516 ],
        [ 4.7203965 ],
        [-6.0726805 ],
        [ 8.688414  ],
        [ 1.528385  ],
        [ 4.4781084 ],
        [ 6.603953  ],
        [-0.8712809 ]], dtype=float32)>)

In [6]:
# keras是TensorFlow的高级API
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

In [7]:
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

In [8]:
loss = tf.keras.losses.MeanSquaredError()

In [10]:
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [11]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

2025-08-03 14:56:56.363575: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-08-03 14:56:56.485642: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


epoch 1, loss 0.000236
epoch 2, loss 0.000098
epoch 3, loss 0.000097


In [14]:
w = net.get_weights()[0]
print('w的估计误差：', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('b的估计误差：', true_b - b)

w的估计误差： tf.Tensor([-0.00017095 -0.00013328], shape=(2,), dtype=float32)
b的估计误差： [-0.000319]
